#!/usr/bin/env python3
"""Generate docs/TOOLS.md from the tool schemas (single source of truth)."""
import importlib.util
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

GROUPS = [("A. Inspect", 5), ("B. Cut & time", 8), ("C. Picture", 9),
          ("D. Overlays & text", 6), ("E. Audio", 8), ("F. Export & check", 6)]


def load():
    spec = importlib.util.spec_from_file_location("hermes_video_editor", ROOT / "__init__.py",
                                                  submodule_search_locations=[str(ROOT)])
    mod = importlib.util.module_from_spec(spec)
    sys.modules["hermes_video_editor"] = mod
    spec.loader.exec_module(mod)
    from hermes_video_editor.schemas import TOOLS
    return TOOLS


def typ(p):
    t = p.get("type", "")
    t = "/".join(t) if isinstance(t, list) else t
    return "%s (%s)" % (t, "|".join(map(str, p["enum"]))) if "enum" in p else t


def render(tools):
    out = ["# Tool reference (%d tools)" % len(tools), "",
           "Generated by `scripts/gen_docs.py` from the tool schemas. Do not edit by hand.", "",
           "Every tool returns a JSON string: `{\"ok\": true, \"output\": ..., \"duration_s\": ..., \"info\": {...}}` "
           "or `{\"ok\": false, \"error\": ..., \"hint\": ..., \"ffmpeg_stderr_tail\": ...}`. "
           "`duration_s` is the length of the OUTPUT media in seconds; processing time is `info.elapsed_s`.", ""]
    it = iter(tools)
    for title, count in GROUPS:
        out += ["## " + title, ""]
        for _ in range(count):
            t = next(it)
            s = t["schema"]
            params = s["parameters"]["properties"]
            req = set(s["parameters"].get("required", []))
            out += ["### `%s`" % t["name"], "", s["description"], "", "| Parameter | Type | Required | Description |",
                    "|---|---|---|---|"]
            for k, p in params.items():
                d = p.get("description", "").replace("|", "\\|").replace("\n", " ")
                if "default" in p:
                    d += " Default: `%s`." % p["default"]
                out.append("| `%s` | %s | %s | %s |" % (k, typ(p), "yes" if k in req else "", d))
            out.append("")
    return "\n".join(out)


if __name__ == "__main__":
    text = render(load())
    target = ROOT / "docs" / "TOOLS.md"
    if "--check" in sys.argv:
        sys.exit(0 if target.read_text(encoding="utf-8") == text else 1)
    target.write_text(text, encoding="utf-8")
    print("wrote", target)
